Importamos Librerias

In [1]:
import pandas as pd
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
import numpy as np

Realizamos la ingesta de los datos. 

In [2]:
df_test = pd.read_csv("../datasets/hospitalizaciones_test.csv")
df_train = pd.read_csv("../datasets/hospitalizaciones_train.csv")

Vemos el tamaño y dimensiones de los dataframe. Se observa que train tiene una columna mas que test. 

In [3]:
df_train.shape

(410000, 15)

In [4]:
df_test.shape

(90000, 14)

Vemos las columnas.

In [5]:
df_test.columns

Index(['Available Extra Rooms in Hospital', 'Department', 'Ward_Facility_Code',
       'doctor_name', 'staff_available', 'patientid', 'Age', 'gender',
       'Type of Admission', 'Severity of Illness', 'health_conditions',
       'Visitors with Patient', 'Insurance', 'Admission_Deposit'],
      dtype='object')

In [6]:
df_train.columns

Index(['Available Extra Rooms in Hospital', 'Department', 'Ward_Facility_Code',
       'doctor_name', 'staff_available', 'patientid', 'Age', 'gender',
       'Type of Admission', 'Severity of Illness', 'health_conditions',
       'Visitors with Patient', 'Insurance', 'Admission_Deposit',
       'Stay (in days)'],
      dtype='object')

In [7]:
df_test.head(1)

Available Extra Rooms in Hospital  Department Ward_Facility_Code  \
0                                  3  gynecology                  F   

  doctor_name  staff_available  patientid    Age  gender Type of Admission  \
0   Dr Olivia               10       2858  21-30  Female            Trauma   

  Severity of Illness health_conditions  Visitors with Patient Insurance  \
0            Moderate             Other                      2        No   

   Admission_Deposit  
0        4749.640225

Verificamos si hay valores faltantes.

In [8]:
df_train.count()

Available Extra Rooms in Hospital    410000
Department                           410000
Ward_Facility_Code                   410000
doctor_name                          410000
staff_available                      410000
patientid                            410000
Age                                  410000
gender                               410000
Type of Admission                    410000
Severity of Illness                  410000
health_conditions                    410000
Visitors with Patient                410000
Insurance                            410000
Admission_Deposit                    410000
Stay (in days)                       410000
dtype: int64

In [9]:
df_test.count()

Available Extra Rooms in Hospital    90000
Department                           90000
Ward_Facility_Code                   90000
doctor_name                          90000
staff_available                      90000
patientid                            90000
Age                                  90000
gender                               90000
Type of Admission                    90000
Severity of Illness                  90000
health_conditions                    90000
Visitors with Patient                90000
Insurance                            90000
Admission_Deposit                    90000
dtype: int64

Analizamos los valores dentro de las columnas, tipos de datos y si hay errores evidentes.

In [10]:
df_train['Available Extra Rooms in Hospital'].unique()

array([ 4,  2,  7,  3,  5, 10,  6,  1, 21,  8, 11, 13,  9, 14, 24,  0, 12,
       20], dtype=int64)

In [11]:
df_train['Department'].unique()

array(['gynecology', 'anesthesia', 'TB & Chest disease', 'radiotherapy',
       'surgery'], dtype=object)

In [12]:
df_train['Ward_Facility_Code'].unique()

array(['D', 'B', 'E', 'F', 'A', 'C'], dtype=object)

In [13]:
df_train['doctor_name'].unique()

array(['Dr Sophia', 'Dr Olivia', 'Dr Mark', 'Dr John', 'Dr Sarah',
       'Dr Sam', 'Dr Nathan', 'Dr Simon', 'Dr Isaac'], dtype=object)

In [14]:
df_train['staff_available'].unique()

array([ 0,  2,  8,  7, 10,  5,  9,  3,  6,  4,  1], dtype=int64)

In [15]:
df_train['Age'].unique()

array(['41-50', '31-40', '21-30', '71-80', '11-20', '51-60', '61-70',
       '81-90', '91-100', '0-10'], dtype=object)

In [16]:
df_train['gender'].unique()

array(['Female', 'Male', 'Other'], dtype=object)

In [17]:
df_train['Type of Admission'].unique()

array(['Trauma', 'Urgent', 'Emergency'], dtype=object)

In [18]:
df_train['Severity of Illness'].unique()

array(['Extreme', 'Minor', 'Moderate'], dtype=object)

In [19]:
df_train['Visitors with Patient'].unique()

array([ 4,  2,  3, 11,  9,  6,  8, 12,  5,  1, 14,  7, 13, 10, 22, 18,  0,
       16, 20, 21, 19, 23, 15, 24, 17, 30, 32, 25], dtype=int64)

In [20]:
df_train['health_conditions'].unique()

array(['Diabetes', 'Heart disease', 'None', 'Other', 'Asthama',
       'High Blood Pressure'], dtype=object)

In [21]:
df_train['Insurance'].unique()

array(['Yes', 'No'], dtype=object)

In [22]:
df_train['Admission_Deposit'].unique()

array([2966.408696, 3554.835677, 5624.733654, ..., 3816.99421 ,
       3841.577491, 4329.046412])